[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
afterlife = "4pKCmz43y8apgNqoAZVhYba11r5MyW6fiDnH3WGb16Uu"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
